import Head from "next/head";
import Image from "next/image";
import {Inter} from "next/font/google";
import styles from "../styles/Home.module.css";

import Blog from "../components/blog/blog";
import Sliders from "../components/sliders/sliders";
import Reviews from "../components/reviews/reviews";
import Tours from "../components/tours/tours";
import Banner from "../components/banders/banner";
import App from "../components/layouts/app";
import {useDispatch, useSelector} from "react-redux";
import {useEffect} from "react";
import {getBlogs} from "../store/blog/actions";
import {getReviews} from "../store/reivews/actions";
import {getTours} from "../store/tour/actions";
import {getSlides} from "../store/slides/actions";
import {getGalleries} from "../store/gallery/actions";


const inter = Inter({subsets: ["latin"]});

export default function Home() {
    const blogs = useSelector((state) => state.blog.blogs);
    const reviews = useSelector((state) => state.review.reviews);
    const tours = useSelector((state) => state.tour.tours);
    const slides = useSelector((state) => state.slide.slides);
    const galleries = useSelector((state) => state.gallery?.galleries);

    const dispatch = useDispatch();
    useEffect(() => {
        dispatch(getBlogs.request());
        dispatch(getReviews.request());
        dispatch(getTours.request());
        dispatch(getSlides.request())
        dispatch(getGalleries.request())
    }, [dispatch]);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <App>
                    <Banner slides={slides}/>
                    <Tours tours={tours}/>
                    <Reviews reviews={reviews}/>
                    <Blog blogs={blogs}/>
                    <Sliders galleries={galleries}/>
                </App>
            </main>
        </>
    );
}
